# skills.py

SKILLS = [
    "python",
    "java",
    "c++",
    "sql",
    "html",
    "css",
    "javascript",
    "react",
    "node",
    "machine learning",
    "deep learning",
    "data analysis",
    "pandas",
    "numpy",
    "tensorflow",
    "flask",
    "django",
    "api",
    "git",
    "linux",
    "dl",
    "ml",
    "ai",
    "artificial intelligence",
    "data science",
    "js",
    "reactjs",
    "angular",
    "vue",
    "nodejs",
    "express",
    "mongodb",
    "postgresql",
    "aws",
    "azure",
    "gcp",
    "docker",
    "kubernetes",
    "ci/cd",
    "agile",
    "scrum",
    "communication",
    "teamwork",
    "problem-solving",
    "leadership",
    "reactJS",
    "angularJS",
    "vueJS",
    "nodeJS",
    "expressJS",
    "mongodb",
    "postgresql",
    "aws",
    "azure",
    "gcp",
    "docker",
    "kubernetes",
    "ci/cd",
    "agile",
    "scrum",
    "communication",
    "teamwork",
    "problem-solving",
    "leadership",
]
